apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-python-app
  labels:
    app: sample-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-python-app  # Indentation corrigée ici
  template:
    metadata:
      labels:
        app: sample-python-app
    spec:
      containers:
      - name: python-app
        image: mohamedbolydev/python-sample-app-demo:v1
        volumeMounts:
        - name: db-connection # nom du volume que nous allons monter
          mountPath: /opt # chemin de montage du volume, on peut utiliser n'importe quel chemin de notre image du pod
        ports:
        - containerPort: 8000
      volumes:
      - name: db-connection # nom du volume que nous allons monter
        configMap:
          name: test-cm # nom de la ConfigMap lie au volume




